services:
  database:
    container_name: shopping_database
    environment:
      MYSQL_DATABASE: "${DATABASE_NAME}"
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
    image: mysql:8
    ports:
      - 3306:3306
